export enum ENUM_COMMENT_STATUS_CODE_ERROR {
    COMMENT_NOT_FOUND_ERROR = 5500,
    COMMENT_NOT_OWNER_ERROR = 5501,
    COMMENT_NOT_FOUND_CATEGORY_ERROR = 5502,
    COMMENT_NOT_FOUND_TAG_ERROR = 5503,
}
